### ISSUE TITLE
Question: Can the rope interact with RigidBody2Ds?

### ISSUE THREAD

**Issue by atorstling** [mphe/GDNative-Ropesim#13]
Hi! Sorry if this is the wrong forum for questions, I was just wondering if it's possible to interact with physical bodies, like for instance hanging a weight at the end of the rope, that in turn could get affected by other physic bodies? I had a quick look at RopeInteraction, but it didn't seem to use physical quantities like forces, torque etc. 

Thank you in advance

**Comment by mphe** [comment]
This is the right place for questions :)
Ropes themselves can not interact with physics objects. However, attaching a physic body to a rope which in turn can react to other physic bodies and affect the rope accordingly should be possible.
You can look at the `rope_swinging.tscn` example, which shows a similar use-case. Since I'm currently in the process of providing more examples, I'll try to create one and report back.

>  had a quick look at RopeInteraction, but it didn't seem to use physical quantities like forces, torque etc.

The physics in this plugin are completely unrelated to the internal Godot physics.
The rope simulation simply uses position deltas to determine the current velocity, so any movement of any rope point causes a corresponding physical behavior.

**Comment by mphe** [comment]
I just added an example project that demonstrates attaching RigidBodies to a rope. See `rigidbody_rope_attachment.tscn`.
You can get the most recent build [here](https://github.com/mphe/GDNative-Ropesim/actions/runs/10126907467).

I'll close this issue because it is technically solved, but if you have further questions, let me know.
