### ISSUE TITLE
a Simple hanging mechanic

### ISSUE THREAD

**Issue by Zheromaro** [mphe/GDNative-Ropesim#14]
Hello, I hope my question isn't complicated 

I hope if the RopeCollisionShapeGenerator Node could give you an information about where in the rope the collision happened
and then feed this information in the RopeAnchor Node

which will make implementing the hanging mechanic very simple

**Comment by mphe** [comment]
The `RopeCollisionShapeGenerator` is only responsible for generating `CollisionShape`s. It has nothing to do with collision detection.
You can use `Rope.get_nearest_point_index()` to get the nearest point index to a given point, then feed this index into `Rope.get_point_perc()` to get a fractional value that you can use in `RopeAnchor`.

It is a bit cumbersome but I'm planning to add a helper function to `RopeAnchor`. `RopeHandle` already has them (`use_nearest_position`, `use_nearest_position_to_point`).

I recently made a larger update which also includes various example scenes.
However, I haven't released it yet to the Asset Library because I'm still working on it.
You can get the current version from the [latest build workflow](https://github.com/mphe/GDNative-Ropesim/actions/runs/10066503859).
You can take a look at the `rope_swinging` example, which demonstrates a similar use-case.

**Comment by mphe** [comment]
> It is a bit cumbersome but I'm planning to add a helper function to RopeAnchor. RopeHandle already has them (use_nearest_position, use_nearest_position_to_point).

I just pushed an update and now both `RopeAnchor` and `RopeHandle` have these utility functions.

I'll close this issue because it is technically solved, but if you have further questions, let me know.

**Comment by Zheromaro** [comment]
thanks man :) 

you did a very good job
this addon should be in the base version of godot

**Comment by mphe** [comment]
Thanks! Glad you like it :)
