### ISSUE TITLE
Remove anchor from rope at runtime

### ISSUE THREAD

**Issue by BenjaminOrenstein** [mphe/GDNative-Ropesim#20]
It seems to not be possible to remove an anchor/handle from a body at runtime?

.set_enable(false) disables some but not all properties of the anchor/handle but is maybe not this methods purpose?

Thank you

EDIT: I'm worried my tone comes off as aggressive - I'm not, I'm just unclear on if this is supposed to be possible and I'm missing something or if set_enable isn't quite working.  Thank you.

**Comment by BenjaminOrenstein** [comment]
Right now I have a 'boat' connected to a 'dock' by a 'rope'. When that 'rope' gets pulled hard enough I want to disconnect the 'rope' from the 'boat' so that it falls into the water.

I use a signal to make the connection:

```
func _on_rope_interaction_on_movement_request(target: Node2D, anchor: RopeAnchor) -> void:
	if anchor.enable: #This if statement doesn't do anything
		target.global_position = anchor.global_position
	
	if(current_drag_force.length()*get_physics_process_delta_time() > 5): 
		anchor.set_enable(false)

```
When the anchor is disabled, the rope still moves with the boat.  However, some things such as max_endpoint no longer impact the ropes movement, and the rope doesn't pull on the boat. This may be as intended, but if so is there a way to disconnect the rope from the boat?

I took a video of what happens when I disable the anchor:

https://github.com/user-attachments/assets/88666e2c-931f-4abf-a8d3-e25ca9209d4f

I can make a minimal example project when I get home from work if that is helpful.

Thank you

**Comment by BenjaminOrenstein** [comment]
Sorry - I misspoke and am using a RopeHandle.

I've attached a project.  At this point, I'm pretty sure I'm just missing something, but I'm not 100% sure it's not a bug on your end?  If you find a chance to look I would appreciate it.

[test_project.zip](https://github.com/user-attachments/files/17460264/test_project.zip)

**Comment by mphe** [comment]
[test_project.zip](https://github.com/user-attachments/files/17465539/test_project.zip)

I fixed it, it was indeed a problem with your setup. You almost had it right.
Only thing you need is a `RopeInteraction` with its target set to the boat object.
This allows the boat to pull on the rope but also allows the rope to stop the boat from pulling futher than allowed.
Internally this uses a combination of `RopeAnchor` and `RopeHandle` as you might have already noticed.
When the rope should break, you just disable the `RopeInteraction`. No need to implement a custom handler for `RopeInteraction`, just check the force in `_physics_process`.

If you have further questions, let me know.

**Comment by BenjaminOrenstein** [comment]
Great thank you.  I see what I was misunderstanding now!

It's outside the scope of this question (and github issues in general) - but is it possible to break a rope in two at certain point with this tool?  I don't believe enough is exposed to duplicate a rope's components into two ropes but figured I'd ask what you thought.

**Comment by mphe** [comment]
Glad I could help!
I'm closing this issue since the original problem has been solved.
If you have further questions, you can still keep commenting here.

Github Issues are currently, besides reporting issues, the only place to discuss and ask questions about this plugin, so feel free to do so.
I'm also very curious about new and interesting ways to use this addon :).

Breaking a rope in two is only possible with some trickery. I just created a new example scene which demonstrates how to accomplish this.
See the `breakable_rope` example (it's not on the Asset Library, yet, you have to get it from Github).
Essentially, it uses three ropes: one large rope and two smaller ropes that are constrained to the first rope. When the first rope exceeds a certain length, it will be hidden and disabled while the other two ropes become visible, giving the illusion of the rope breaking.
