### ISSUE TITLE
Parser error extending BaseRopeTool2D

### ISSUE THREAD

**Issue by ricksto1987** [mphe/GDNative-Ropesim#21]
Ocassionally when running from the editor I get this parse error in GD script

![image](https://github.com/user-attachments/assets/d0701eca-ac78-4d56-b2ac-ff62f9998af2)

It seems some form of race condition is happening but my GD script knowledge is very limited. My project is using C# and my scene has a child node of type Rope. I have another node of type RopeAnchor in the scene.

![image](https://github.com/user-attachments/assets/a4614fb6-8f22-4927-9dd2-9e8dcce72395)

I'm using version 1.3 of RopeSim

**Comment by mphe** [comment]
This is pretty strange. I never encountered this problem and I don't understand why it would appear in the first place. This is also a fairly normal usecase.
Can you reproduce this bug consistently? If so, could you try to upload a minimal reproduction project?
Which Godot version are you using?

**Comment by mphe** [comment]
Hm, this could indeed be the problem.
All rope related tools including ropes themselves reference in some way `NativeRopeServer`, which is a singleton (similar to PhysicsServer, VisualServer, ...).
If `NativeRopeServer` has not yet been loaded, but you try to instantiate the scene with rope scripts, you will get an error, because all scripts that directly reference `NativeRopeServer` fail to parse and load.

I'd suggest to not instantiate scenes from autoloads unless you now for sure that all other autoloads and singletons have been loaded already.
What I do, for example, I have an "init" scene that is loaded on start, which is completely empty besides a `ColorRect` for background and a single node that loads the actual main scene in `_ready()`.
This way you can be sure everything has been loaded and initialized correctly.

**Comment by ricksto1987** [comment]
Thanks for the description of under the hood very helpful!

Yea, its something where I'm moving away from, as it turns out my main scene calls a method after ready which wires up the map nodes for features and in there I now instantiate my scene containing the Rope node - which after reading your suggestions follows a similar concept. So far I have not had the issue happen so I'm hopeful this has solved it :)

Thanks for your help!
