### ISSUE TITLE
Adding Stiffness Ignores Gravity

### ISSUE THREAD

**Issue by CommitThis** [mphe/GDNative-Ropesim#22]
Hello @mphe, I have noticed that when adding a stiffness amount to a rope where the gravity vector is not down, the stiffness simulation will cause the rope to tend towards down.

Now, my vector math is not brilliant, and I couldn't quite glean the meaning of `parent_seg_dir` as it seemed to involve the overall transform of the rope, but I figured that changing the basis transform to use `gravity_direction` instead of `VECTOR_DOWN` seems to address the issue.

**Comment by mphe** [comment]
Hi, 

at the moment, when stiffness is active, the rope will try to snap back into downwards direction, rotated by the node's transform. This is intended, because the desired stiffness direction does not always correlate to the gravity direction, e.g. in a zero-gravity space. Also in general, when bending an object in real life, it will not necessarily snap back into gravity direction, e.g. consider a catapult or a bow and arrow.
That means if you want to change the stiffness direction, rotate the rope node to face the desired direction.

It is a bit unintuitive but the behavior is documented in the stiffness property and I don't want to break existing code by changing it.
Could you let me know a little more about your project and what you are trying to achieve?
I'm considering adding another property to make it more intuitive.

**Comment by CommitThis** [comment]
I guess I thought "downwards" was with respect to gravity, but it does make much more sense now that you've explained it.

My project will be using the ropes as cables to connect bits of fixed equipment together, so stiffness will come into it, but altered gravity will not; I was just experimenting with the rope properties when I discovered the behaviour.
