### ISSUE TITLE
Gravity should be a Vector2

### ISSUE THREAD

**Issue by ArchLinus** [mphe/GDNative-Ropesim#8]
Currently gravity is a float. Some games like to change the direction of gravity for various reasons.

Alternatively, to not break compatibility, an additional `gravity_direction` vector can be provided. It might also be worthwhile to just grab gravity from the physics engine itself instead using its own specific gravity value.

**Comment by mphe** [comment]
Absolutely, don't know why I didn't implement this as vector in the first place.

Will look into it in the next few days.

**Comment by mphe** [comment]
Done in recent commit.
You can grab the build from the [latest build workflow](https://github.com/mphe/GDNative-Ropesim/actions/runs/9032300610).
I will create a release and the update will be on the Asset Library in a few days.

> It might also be worthwhile to just grab gravity from the physics engine itself instead using its own specific gravity value.

I'd rather not do this, because these are two completely different systems.
Another option would be to provide a kind of physics material resource for ropes that can be shared.
However, I'm not sure which properties should be included in such a material and which not.
It also only makes sense if there are a lot ropes of the same kind whose properties need to be changed dynamically at runtime.
Hence, this is a problem for the future when there is a certain demand for it.
